version: '3.4'

services:
  auctiondb:
    image: postgres

  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile


volumes:
  postgres_data:
   
  