version: '3.4'

services:
  auctiondb:
    image: postgres

  searchdb:
    image: mongo

  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine   


  searchservice:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile

volumes:
  postgres_data:
  mongo_data:
   
  
