version: '3.4'

services:
  auctiondb:
    container_name: auctiondb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=AuctionDb
    restart: unless-stopped
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  searchdb:
    container_name: searchdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/var/lib/mongodb/data

  auctionservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
 
  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    ports:
        - "5672:5672"
        - "15672:15672"

  searchservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

